name: Fetch-Currencies

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for branch 1 and on start directory, command.txt file changes or by manually running the workflow from actions tab
on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

  workflow_dispatch:
  
env: # Or as an environment variable
  currlink: ${{ secrets.CURRLINK }}
  cryptolink: ${{ secrets.CRYPTOLINK }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Partial clone
      - name: Partial clone
        shell: bash
        run: |
          brew install coreutils
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git clone --no-checkout --sparse $REPO .
          git sparse-checkout add 'latest/*' \'`gdate -u +"%Y-%m-%d" --date='-1 year -5 month -10 day'`/*\'
          git checkout

      # Install git-filter-repo
      - name: Install git-filter-repo
        shell: bash
        run: |
          brew install git-filter-repo

      # Delete old folders
      - name: Delete old folders
        shell: bash
        run: |
          git remote -v
          git filter-repo --force --invert-paths --path `gdate -u +"%Y-%m-%d" --date='-1 year -5 month -10 day'`
          
      - name: Get cache directory for npm
        id: cache-dir
        shell: bash
        run: echo "::set-output name=npmcache::$(npm config get cache)"

      - name: Trying to use the old cache if available
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-dir.outputs.npmcache }}
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci
          
      - name: Running the command
        run: node currscript.js

      # commiting and pushing changes
      - name: commit and push
        shell: bash
        run: |
          export GIT_TRACE_PACKET=1
          export GIT_TRACE=1
          export GIT_CURL_VERBOSE=1
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git config --global gc.auto 0
          git config --global gc.autodetach false
          git config --global http.postBuffer 2147483648
          git add --sparse -A
          git commit -m 'Update Currencies'
          git remote add origin ${{ github.repositoryUrl }}
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive
          git push --force --all
          git push --force --tags
